extends: eslint:recommended
parseOptions:
  ecmaVersion: 6
env:
  browser: true
  node: true
  es6: true
  nashorn: true
  greasemonkey: true
  jquery: true
rules:
  no-console: off
  no-constant-condition: off
  no-debugger: off
  no-empty: off
  no-extra-parens: error
  valid-jsdoc: error
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  complexity: # untested
    - error
    - 10
  consistent-return: error # untested
  curly: error
  dot-location: error
  dot-notation: error
  no-alert: error
  no-caller: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implied-eval: error
  no-iterator: error
  no-lone-blocks: error
  no-multi-spaces: error
  no-multi-str: error
  no-native-reassign: error
  # only warns about using the new operator when you don't assign it to a variable, doesn't disable
  # new in general
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-void: error
  no-with: error
  wrap-iife: error
  yoda: error
  strict: error
  no-label-var: error # untested
  no-shadow-restricted-names: error
  no-undef-init: error
  callback-return: error # untested
  global-require: error
  handle-callback-err: error # untested
  no-mixed-requires: error # untested
  no-new-require: error
  no-path-concat: error
  # no-sync: error
  array-bracket-spacing: error
  block-spacing: error
  brace-style: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  eol-last: error
  func-style:
    - error
    - declaration
  indent:
    - error
    - 2
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  max-statements-per-line: error # untested
  new-cap: error
  new-parens: error
  no-bitwise: error
  no-inline-comments: error
  no-lonely-if: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 1
  no-negated-condition: error
  no-new-object: error
  no-spaced-func: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  operator-assignment: error
  quote-props:
    - error
    - as-needed
  quotes: error
  semi: error
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
  space-infix-ops: error # untested
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  spaced-comment: error
  arrow-body-style: error # untested
  arrow-parens: error
  arrow-spacing: error
  generator-star-spacing:
    - error
    - after
  no-confusing-arrow: error
  no-duplicate-imports: error # untested
  no-useless-computed-key: error
  no-useless-constructor: error # untested
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-reflect: error # untested
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error # untested
  template-curly-spacing: error
  yield-star-spacing: error # untested
